---

- name: Configure /etc/rsyslog.conf
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    mode: 0640
    owner: root
    group: root
  notify: [ 'Restart rsyslog' ]

- name: Configure logrotate
  copy:
    src: rsyslog-own
    dest: /etc/logrotate.d/rsyslog-own
    mode: 0640
    owner: root
    group: root
  with_items:
    - "rsyslog-own"
    - "defaults-own"
