---

- name: Configure /etc/rsyslog.conf
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    mode: 0640
    owner: root
    group: root
  notify: [ 'Restart rsyslog' ]

- name: Configure logrotate
  copy:
    src: "{{ item }}"
    dest: "/etc/logrotate.d/{{ item }}"
    mode: 0640
    owner: root
    group: root
  with_items:
    - "rsyslog-own"
    - "defaults-own"

- name: Get a list of all files under /etc/logrotate.d/
  raw: find /etc/logrotate.d/ -type f
  register: service_rsyslog_logrotate_files

- name: Set nocompess for all files under /etc/logrotate.d/
  replace:
    dest: "{{ item }}"
    replace: '\1 no\2'
    regexp: '^(\s+)(compress)$'
  with_items: service_rsyslog_logrotate_files.stdout_lines
