---

- name: Configure /etc/rsyslog.conf
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify: [ 'Restart rsyslog' ]
  with_items:
    - 'etc/rsyslog.conf'

- name: Configure logrotate
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify: [ 'Restart rsyslog' ]
  with_items:
    - 'etc/logrotate.d/rsyslog-own'
    - 'etc/logrotate.d/defaults-own'

- name: Get a list of all files under /etc/logrotate.d/
  raw: find /etc/logrotate.d/ -type f
  register: service_rsyslog_logrotate_files

- name: Set nocompess for all files under /etc/logrotate.d/
  replace:
    dest: '{{ item }}'
    replace: '\1 no\2'
    regexp: '^(\s+)(compress)$'
  with_items: service_rsyslog_logrotate_files.stdout_lines
